[package]
name = "tung-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.8.0"
pest_derive = "2.8.0"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.12"
lazy_static = "1.4.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
