[package]
name = "tung-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.8.0"
pest_derive = "2.8.0"
miette = { version = "7.6.0", features = ["fancy"] }
clap = { version = "4.5.38", features = ["derive"] }
regex = "1.11.1"
